// Package ldfrag writes GNU ld MEMORY fragments describing free ROM space.
package ldfrag

import (
	"fmt"
	"io"

	"mdrom/internal/rom"
)

// RegionName returns the linker memory name for r: ROM_FREE for the usable region, ROM_GAP_<origin> otherwise.
func RegionName(r, free rom.Region) string {
	if r.Start == free.Start && r.End == free.End {
		return "ROM_FREE"
	}
	return fmt.Sprintf("ROM_GAP_%06X", r.Start)
}

// Write emits a MEMORY block for the free region and each interior gap.
func Write(w io.Writer, free rom.Region, interior []rom.Region) error {
	lines := []string{"/* Generated by mdrom free. Do not edit. */", "MEMORY", "{"}
	for _, r := range append([]rom.Region{free}, interior...) {
		lines = append(lines, fmt.Sprintf("  %s (rx) : ORIGIN = 0x%06X, LENGTH = 0x%06X", RegionName(r, free), r.Start, r.Len()))
	}
	lines = append(lines, "}")
	for _, l := range lines {
		if _, err := io.WriteString(w, l+"\n"); err != nil {
			return err
		}
	}
	return nil
}
