package ldfrag_test

import (
	"bytes"
	"testing"

	"mdrom/internal/ldfrag"
	"mdrom/internal/rom"
)

func TestWriteFragment(t *testing.T) {
	free := rom.Region{Start: 0x0FFFF0, End: 0x200000, Kind: rom.Expansion}
	gaps := []rom.Region{{Start: 0x042334, End: 0x0427B4, Kind: rom.Interior}}
	var buf bytes.Buffer
	if err := ldfrag.Write(&buf, free, gaps); err != nil {
		t.Fatal(err)
	}
	want := "/* Generated by mdrom free. Do not edit. */\n" +
		"MEMORY\n" +
		"{\n" +
		"  ROM_FREE (rx) : ORIGIN = 0x0FFFF0, LENGTH = 0x100010\n" +
		"  ROM_GAP_042334 (rx) : ORIGIN = 0x042334, LENGTH = 0x000480\n" +
		"}\n"
	if buf.String() != want {
		t.Fatalf("fragment:\n%s\nwant:\n%s", buf.String(), want)
	}
}

func TestRegionName(t *testing.T) {
	free := rom.Region{Start: 0x100000, End: 0x200000}
	if got := ldfrag.RegionName(free, free); got != "ROM_FREE" {
		t.Errorf("RegionName(free) = %q", got)
	}
	gap := rom.Region{Start: 0x042334, End: 0x0427B4}
	if got := ldfrag.RegionName(gap, free); got != "ROM_GAP_042334" {
		t.Errorf("RegionName(gap) = %q", got)
	}
}
