package main

import (
	"bytes"
	"encoding/binary"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"mdrom/internal/rom"
	"mdrom/internal/testrom"
)

// writeSynth writes a synthetic image of the given size into a temp dir and returns its path.
func writeSynth(t *testing.T, size int) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "base.md")
	if err := os.WriteFile(path, testrom.Synth(size), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

// writeSynthWithGap writes a synthetic image with bytes 0x1000..0x1800 zeroed,
// an interior gap the tests can target with --interior, and returns its path.
func writeSynthWithGap(t *testing.T, size int) string {
	t.Helper()
	img := testrom.Synth(size)
	for i := 0x1000; i < 0x1800; i++ {
		img[i] = 0
	}
	path := filepath.Join(t.TempDir(), "gap.md")
	if err := os.WriteFile(path, img, 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

// mustRead reads path or fails the test.
func mustRead(t *testing.T, path string) []byte {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return data
}

// mustWrite writes data to path or fails the test.
func mustWrite(t *testing.T, path string, data []byte) {
	t.Helper()
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}
}

// exec runs the CLI in-process and returns exit code, stdout, stderr.
func exec(args ...string) (int, string, string) {
	var out, errb bytes.Buffer
	code := run(args, &out, &errb)
	return code, out.String(), errb.String()
}

func TestNoArgsPrintsUsage(t *testing.T) {
	code, _, stderr := exec()
	if code != 2 || !strings.Contains(stderr, "usage:") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestUnknownCommand(t *testing.T) {
	code, _, stderr := exec("frobnicate")
	if code != 2 || !strings.Contains(stderr, "unknown command") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInfoReportsChecksumOK(t *testing.T) {
	base := writeSynth(t, 0x100000)
	code, stdout, stderr := exec("info", base)
	if code != 0 {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	for _, want := range []string{"domestic:  SYNTHETIC TEST ROM", "rom:       0x000000-0x0FFFFF", "sram:      none", "region:    U", " OK"} {
		if !strings.Contains(stdout, want) {
			t.Errorf("stdout lacks %q:\n%s", want, stdout)
		}
	}
}

func TestInfoReportsChecksumMismatch(t *testing.T) {
	base := writeSynth(t, 0x100000)
	img := mustRead(t, base)
	img[0x1000] ^= 0xFF
	mustWrite(t, base, img)
	code, stdout, _ := exec("info", base)
	if code != 0 || !strings.Contains(stdout, "MISMATCH") {
		t.Fatalf("code %d stdout %q", code, stdout)
	}
}

func TestInfoMissingFile(t *testing.T) {
	code, _, stderr := exec("info", "/nonexistent/rom.md")
	if code != 1 || !strings.Contains(stderr, "mdrom:") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestParseSize(t *testing.T) {
	for in, want := range map[string]int{"2097152": 0x200000, "0x200000": 0x200000} {
		if got, err := parseSize(in); err != nil || got != want {
			t.Errorf("parseSize(%q) = %d, %v", in, got, err)
		}
	}
	for _, bad := range []string{"-1", "0", "abc", ""} {
		if _, err := parseSize(bad); err == nil {
			t.Errorf("parseSize(%q) accepted", bad)
		}
	}
}

func TestFreeReportsExpansionAndWritesFragment(t *testing.T) {
	base := writeSynth(t, 0x100000)
	ld := filepath.Join(t.TempDir(), "free.ld")
	code, stdout, stderr := exec("free", base, "--size", "0x200000", "--ld", ld)
	if code != 0 {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	for _, want := range []string{"0x100000  0x200000  0x100000  0xFF  expansion", "usable: 1048576 bytes at 0x100000", "headroom: 2097152 bytes below max size 4194304", "wrote " + ld} {
		if !strings.Contains(stdout, want) {
			t.Errorf("stdout lacks %q:\n%s", want, stdout)
		}
	}
	got := mustRead(t, ld)
	want := "/* Generated by mdrom free. Do not edit. */\nMEMORY\n{\n  ROM_FREE (rx) : ORIGIN = 0x100000, LENGTH = 0x100000\n}\n"
	if string(got) != want {
		t.Fatalf("fragment:\n%s\nwant:\n%s", got, want)
	}
}

func TestFreeFailsWithoutSpace(t *testing.T) {
	base := writeSynth(t, 0x100000)
	code, _, stderr := exec("free", base)
	if code != 1 || !strings.Contains(stderr, "no usable free space") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestFreeRejectsOversizeUnlessMaxRaised(t *testing.T) {
	base := writeSynth(t, 0x100000)
	if code, _, stderr := exec("free", base, "--size", "0x800000"); code != 1 || !strings.Contains(stderr, "exceeds the maximum cart size") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	if code, _, stderr := exec("free", base, "--size", "0x800000", "--max-size", "0x800000"); code != 0 {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestFreeWarnsOnNonPowerOfTwo(t *testing.T) {
	base := writeSynth(t, 0x100000)
	code, _, stderr := exec("free", base, "--size", "0x180000")
	if code != 0 || !strings.Contains(stderr, "not a power of two") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestFreeInteriorOnlyWithFlag(t *testing.T) {
	path := filepath.Join(t.TempDir(), "gappy.md")
	img := testrom.Synth(0x100000)
	for i := 0x1000; i < 0x1800; i++ {
		img[i] = 0
	}
	mustWrite(t, path, img)
	ld := filepath.Join(t.TempDir(), "free.ld")
	exec("free", path, "--size", "0x200000", "--ld", ld)
	got := mustRead(t, ld)
	if strings.Contains(string(got), "ROM_GAP_") {
		t.Fatal("fragment lists an interior gap without --interior")
	}
	exec("free", path, "--size", "0x200000", "--ld", ld, "--interior")
	got = mustRead(t, ld)
	if !strings.Contains(string(got), "ROM_GAP_001000 (rx) : ORIGIN = 0x001000, LENGTH = 0x000800") {
		t.Fatalf("fragment with --interior:\n%s", got)
	}
}

func TestFreeAcceptsFlagsBeforeROM(t *testing.T) {
	base := writeSynth(t, 0x100000)
	code, stdout, stderr := exec("free", "--size", "0x200000", base)
	if code != 0 || !strings.Contains(stdout, "usable: 1048576 bytes at 0x100000") {
		t.Fatalf("code %d stdout %q stderr %q", code, stdout, stderr)
	}
}

func TestFreeRejectsExtraPositional(t *testing.T) {
	base := writeSynth(t, 0x100000)
	code, _, stderr := exec("free", base, "extra.md", "--size", "0x200000")
	if code != 1 || !strings.Contains(stderr, "unexpected argument \"extra.md\"") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

const pocELF = "../../internal/elfimg/testdata/poc.elf"
const misplacedELF = "../../internal/elfimg/testdata/misplaced.elf"
const buildidELF = "../../internal/elfimg/testdata/buildid.elf"
const hookonlyELF = "../../internal/elfimg/testdata/hookonly.elf"
const hookonlyBuildidELF = "../../internal/elfimg/testdata/hookonly_buildid.elf"
const gapELF = "../../internal/elfimg/testdata/gap.elf"
const atdataELF = "../../internal/elfimg/testdata/atdata.elf"
const unpairedELF = "../../internal/elfimg/testdata/unpaired.elf"
const shortorigELF = "../../internal/elfimg/testdata/shortorig.elf"
const orphanorigELF = "../../internal/elfimg/testdata/orphanorig.elf"

func TestInjectWritesHookCodeAndHeader(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, stdout, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", out, "--size", "0x200000")
	if code != 0 {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	img := mustRead(t, out)
	if len(img) != 0x200000 {
		t.Fatalf("output is %d bytes", len(img))
	}
	if !bytes.Equal(img[0x300:0x306], []byte{0x4E, 0xB9, 0x00, 0x10, 0x00, 0x00}) {
		t.Errorf("hook bytes = %x", img[0x300:0x306])
	}
	if !bytes.Equal(img[0x100000:0x100004], []byte{0x30, 0x2F, 0x00, 0x06}) {
		t.Errorf("code bytes = %x", img[0x100000:0x100004])
	}
	if img[0x100010] != 0xFF {
		t.Errorf("padding after code = %#x, want 0xFF", img[0x100010])
	}
	if end := binary.BigEndian.Uint32(img[0x1A4:]); end != 0x1FFFFF {
		t.Errorf("ROM end = %#x", end)
	}
	if stored := binary.BigEndian.Uint16(img[0x18E:]); stored != rom.Checksum(img) {
		t.Errorf("checksum stored %#x computed %#x", stored, rom.Checksum(img))
	}
	for _, want := range []string{".hook_000300", "0x000300", ".text", "0x100000", "ROM_FREE", "rom end: 0x1FFFFF", "ROM_FREE unused: 1048560 of 1048576 bytes"} {
		if !strings.Contains(stdout, want) {
			t.Errorf("stdout lacks %q:\n%s", want, stdout)
		}
	}
}

func TestInjectRejectsSectionOutsideImage(t *testing.T) {
	base := writeSynth(t, 0x100000)
	img := mustRead(t, base)
	for i := 0xFFF00; i < 0x100000; i++ {
		img[i] = 0xFF // a tail, so free space exists but the code at 0x100000 is off the end
	}
	mustWrite(t, base, img)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", out)
	if code != 1 || !strings.Contains(stderr, ".text") || !strings.Contains(stderr, "outside the 1048576-byte image") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectHookOnlyWithoutFreeSpace(t *testing.T) {
	base := writeSynth(t, 0x100000)
	preImg := mustRead(t, base)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", hookonlyELF, "--out", out)
	if code != 0 {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	img := mustRead(t, out)
	if len(img) != 0x100000 {
		t.Fatalf("output is %d bytes, want 0x100000", len(img))
	}
	if bytes.Equal(img[0x300:0x306], preImg[0x300:0x306]) {
		t.Errorf("bytes at 0x300 unchanged: %x", img[0x300:0x306])
	}
}

func TestInjectNonHookWithoutFreeSpace(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", out)
	if code != 1 || !strings.Contains(stderr, "needs free space") || !strings.Contains(stderr, "--size") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectRejectsOverwriteUnlessAllowed(t *testing.T) {
	base := writeSynth(t, 0x200000) // non-filler all the way through 0x100000
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", out, "--size", "0x400000")
	if code != 1 || !strings.Contains(stderr, ".text") || !strings.Contains(stderr, "non-free byte 0x100000") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	code, stdout, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", out, "--size", "0x400000", "--allow-overwrite")
	if code != 0 || !strings.Contains(stderr, "warning:") || !strings.Contains(stdout, "overwrite") {
		t.Fatalf("code %d stdout %q stderr %q", code, stdout, stderr)
	}
}

func TestInjectRejectsOrigMismatch(t *testing.T) {
	base := writeSynth(t, 0x100000)
	img := mustRead(t, base)
	img[0x302] = 0x60
	mustWrite(t, base, img)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", out, "--size", "0x200000")
	if code != 1 || !strings.Contains(stderr, ".orig_000300") || !strings.Contains(stderr, "4E7160714E71") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	if _, err := os.Stat(out); err == nil {
		t.Fatal("output was written despite the failure")
	}
}

func TestInjectRejectsWrongSHA1(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", out, "--size", "0x200000", "--expect-sha1", "deadbeef")
	if code != 1 || !strings.Contains(stderr, "SHA-1") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectRejectsMisplacedHook(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", misplacedELF, "--out", out, "--size", "0x200000")
	if code != 1 || !strings.Contains(stderr, "0x100010") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectRejectsBuildIDNote(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", buildidELF, "--out", out, "--size", "0x200000")
	if code != 1 || !strings.Contains(stderr, ".note.gnu.build-id") || !strings.Contains(stderr, "--build-id=none") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectHintsBuildIDWithoutFreeSpace(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", hookonlyBuildidELF, "--out", out)
	if code != 1 || !strings.Contains(stderr, "needs free space") || !strings.Contains(stderr, "--build-id=none") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectUsesInteriorGapWithFlag(t *testing.T) {
	base := writeSynthWithGap(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, stdout, stderr := exec("inject", "--base", base, "--elf", gapELF, "--out", out, "--size", "0x200000", "--interior")
	if code != 0 {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	found := false
	for _, line := range strings.Split(stdout, "\n") {
		if strings.HasPrefix(line, ".text") && strings.Contains(line, "ROM_GAP_001000") {
			found = true
		}
	}
	if !found {
		t.Errorf("stdout lacks a .text row with ROM_GAP_001000:\n%s", stdout)
	}
	code, _, stderr = exec("inject", "--base", base, "--elf", gapELF, "--out", out, "--size", "0x200000")
	if code != 1 || !strings.Contains(stderr, "would overwrite non-free byte 0x001000") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectInteriorGapWithoutFreeSpace(t *testing.T) {
	base := writeSynthWithGap(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, stdout, stderr := exec("inject", "--base", base, "--elf", gapELF, "--out", out, "--interior")
	if code != 0 {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	if !strings.Contains(stdout, "ROM_GAP_001000") {
		t.Errorf("stdout lacks ROM_GAP_001000:\n%s", stdout)
	}
	if strings.Contains(stdout, "ROM_FREE unused") {
		t.Errorf("stdout should not report ROM_FREE unused with no usable space:\n%s", stdout)
	}
	img := mustRead(t, out)
	if len(img) != 0x100000 {
		t.Fatalf("output is %d bytes, want 0x100000", len(img))
	}
	want := []byte{0x30, 0x2F, 0x00, 0x06, 0xD0, 0x40, 0xD0, 0x6F, 0x00, 0x06, 0x52, 0x40, 0x4E, 0x75, 0x4E, 0x71}
	if !bytes.Equal(img[0x1000:0x1010], want) {
		t.Errorf("bytes at 0x1000 = %X, want %X", img[0x1000:0x1010], want)
	}
}

func TestInjectAllowOverwriteWithoutFreeSpace(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", gapELF, "--out", out)
	if code != 1 || !strings.Contains(stderr, "needs free space") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	code, stdout, stderr := exec("inject", "--base", base, "--elf", gapELF, "--out", out, "--allow-overwrite")
	if code != 0 || !strings.Contains(stderr, "warning:") {
		t.Fatalf("code %d stdout %q stderr %q", code, stdout, stderr)
	}
	found := false
	for _, line := range strings.Split(stdout, "\n") {
		if strings.HasPrefix(line, ".text") && strings.Contains(line, "overwrite") {
			found = true
		}
	}
	if !found {
		t.Errorf("stdout lacks a .text row with overwrite:\n%s", stdout)
	}
	img := mustRead(t, out)
	want := []byte{0x30, 0x2F, 0x00, 0x06, 0xD0, 0x40, 0xD0, 0x6F, 0x00, 0x06, 0x52, 0x40, 0x4E, 0x75, 0x4E, 0x71}
	if !bytes.Equal(img[0x1000:0x1010], want) {
		t.Errorf("bytes at 0x1000 = %X, want %X", img[0x1000:0x1010], want)
	}
}

func TestInjectReportsBssAndWritesData(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, stdout, stderr := exec("inject", "--base", base, "--elf", atdataELF, "--out", out, "--size", "0x200000")
	if code != 0 {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	if !strings.Contains(stdout, "bss: .bss at 0xFF00") {
		t.Errorf("stdout lacks the bss report:\n%s", stdout)
	}
	found := false
	for _, line := range strings.Split(stdout, "\n") {
		if strings.HasPrefix(line, ".data") && strings.Contains(line, "ROM_FREE") {
			found = true
		}
	}
	if !found {
		t.Errorf("stdout lacks a .data row with ROM_FREE:\n%s", stdout)
	}
	img := mustRead(t, out)
	want := []byte{0x00, 0x01, 0x00, 0x02, 0x00, 0x03, 0x00, 0x04}
	if !bytes.Contains(img[0x100000:0x100100], want) {
		t.Errorf("image lacks %x in 0x100000..0x100100", want)
	}
}

func TestInjectRejectsHookWithoutOrig(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", unpairedELF, "--out", out)
	if code != 1 || !strings.Contains(stderr, ".hook_000300 has no .orig_000300 twin") || !strings.Contains(stderr, "--allow-unverified-hook") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	if _, err := os.Stat(out); err == nil {
		t.Error("output written despite the refusal")
	}
	code, _, stderr = exec("inject", "--base", base, "--elf", unpairedELF, "--out", out, "--allow-unverified-hook")
	if code != 0 || !strings.Contains(stderr, "warning: .hook_000300 has no .orig_000300 twin") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	img := mustRead(t, out)
	if !bytes.Equal(img[0x300:0x306], []byte{0x4E, 0xB9, 0x00, 0x10, 0x00, 0x00}) {
		t.Errorf("hook bytes = %x", img[0x300:0x306])
	}
}

func TestInjectRejectsOrigWithoutHookOrOfWrongSize(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	for elf, want := range map[string]string{
		orphanorigELF: ".orig_000400 has no .hook_000400 twin",
		shortorigELF:  ".hook_000300 is 6 bytes but .orig_000300 is 4",
	} {
		code, _, stderr := exec("inject", "--base", base, "--elf", elf, "--out", out, "--allow-unverified-hook")
		if code != 1 || !strings.Contains(stderr, want) {
			t.Errorf("%s: code %d stderr %q, want %q", elf, code, stderr, want)
		}
	}
}

func TestInjectInteriorAdvisesSizeWithoutFreeSpace(t *testing.T) {
	// The gap sits at 0x2000, so gap.elf's .text at 0x1000 fits no allowed region,
	// and the image has no tail or expansion to grow into.
	img := testrom.Synth(0x100000)
	for i := 0x2000; i < 0x2800; i++ {
		img[i] = 0
	}
	base := filepath.Join(t.TempDir(), "base.md")
	mustWrite(t, base, img)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", gapELF, "--out", out, "--interior")
	if code != 1 || !strings.Contains(stderr, "would overwrite non-free byte 0x001000") || !strings.Contains(stderr, "pass --size to expand the image, or --allow-overwrite") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectRequiresFlags(t *testing.T) {
	if code, _, stderr := exec("inject", "--base", "x"); code != 1 || !strings.Contains(stderr, "--elf") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInjectRejectsExtraPositional(t *testing.T) {
	base := writeSynth(t, 0x100000)
	out := filepath.Join(t.TempDir(), "patched.md")
	code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", out, "--size", "0x200000", "extra.md")
	if code != 1 || !strings.Contains(stderr, `unexpected argument "extra.md"`) {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestHelpFlagExitsTwo(t *testing.T) {
	code, _, stderr := exec("inject", "-h")
	if code != 2 || !strings.Contains(stderr, "-base") || !strings.Contains(stderr, "usage: mdrom inject") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestFreeHelpExitsTwo(t *testing.T) {
	code, _, stderr := exec("free", "-h")
	if code != 2 || !strings.Contains(stderr, "-ld") || !strings.Contains(stderr, "usage: mdrom free") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInfoMissingArgShowsUsage(t *testing.T) {
	code, _, stderr := exec("info")
	if code != 1 || !strings.Contains(stderr, "usage: mdrom info <rom>") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestInfoHelpShowsUsage(t *testing.T) {
	code, _, stderr := exec("info", "-h")
	if code != 2 || !strings.Contains(stderr, "usage: mdrom info <rom>") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestBPSHelpExitsTwo(t *testing.T) {
	code, _, stderr := exec("bps", "-h")
	if code != 2 || !strings.Contains(stderr, "usage: mdrom bps create|apply") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestBPSCreateApplyRoundTrip(t *testing.T) {
	base := writeSynth(t, 0x100000)
	dir := t.TempDir()
	patched := filepath.Join(dir, "patched.md")
	if code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", patched, "--size", "0x200000"); code != 0 {
		t.Fatalf("inject: %s", stderr)
	}
	patch := filepath.Join(dir, "patch.bps")
	code, stdout, stderr := exec("bps", "create", "--base", base, "--target", patched, "--out", patch)
	if code != 0 || !strings.Contains(stdout, "wrote "+patch) {
		t.Fatalf("create: code %d stdout %q stderr %q", code, stdout, stderr)
	}
	info, err := os.Stat(patch)
	if err != nil {
		t.Fatal(err)
	}
	if info.Size() > 256 {
		t.Errorf("patch is %d bytes; expected a tiny patch for a hook plus 16 bytes of code", info.Size())
	}
	applied := filepath.Join(dir, "applied.md")
	code, stdout, stderr = exec("bps", "apply", "--base", base, "--patch", patch, "--out", applied)
	if code != 0 {
		t.Fatalf("apply: code %d stderr %q", code, stderr)
	}
	want := mustRead(t, patched)
	got := mustRead(t, applied)
	if !bytes.Equal(got, want) {
		t.Fatal("applied image differs from the injected image")
	}
	if !strings.Contains(stdout, rom.SHA1Hex(want)) {
		t.Errorf("apply output lacks the SHA-1:\n%s", stdout)
	}
}

func TestBPSApplyRejectsWrongBase(t *testing.T) {
	base := writeSynth(t, 0x100000)
	other := writeSynth(t, 0x100000)
	img := mustRead(t, other)
	img[0x5000] ^= 1
	mustWrite(t, other, img)
	dir := t.TempDir()
	patched := filepath.Join(dir, "patched.md")
	if code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", patched, "--size", "0x200000"); code != 0 {
		t.Fatalf("inject: code %d stderr %q", code, stderr)
	}
	patch := filepath.Join(dir, "patch.bps")
	if code, _, stderr := exec("bps", "create", "--base", base, "--target", patched, "--out", patch); code != 0 {
		t.Fatalf("bps create: code %d stderr %q", code, stderr)
	}
	code, _, stderr := exec("bps", "apply", "--base", other, "--patch", patch, "--out", filepath.Join(dir, "x.md"))
	if code != 1 || !strings.Contains(stderr, "source checksum") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestBPSCreateRejectsExtraPositional(t *testing.T) {
	base := writeSynth(t, 0x100000)
	dir := t.TempDir()
	patched := filepath.Join(dir, "patched.md")
	if code, _, stderr := exec("inject", "--base", base, "--elf", pocELF, "--out", patched, "--size", "0x200000"); code != 0 {
		t.Fatalf("inject: %s", stderr)
	}
	patch := filepath.Join(dir, "patch.bps")
	code, _, stderr := exec("bps", "create", "--base", base, "--target", patched, "--out", patch, "extra.md")
	if code != 1 || !strings.Contains(stderr, `unexpected argument "extra.md"`) {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestBPSUsage(t *testing.T) {
	if code, _, stderr := exec("bps"); code != 1 || !strings.Contains(stderr, "create|apply") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
	if code, _, stderr := exec("bps", "create", "--base", "x"); code != 1 || !strings.Contains(stderr, "--target") {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}

func TestBPSUnknownSubcommand(t *testing.T) {
	code, _, stderr := exec("bps", "frob")
	if code != 1 || !strings.Contains(stderr, `unknown bps command "frob"`) {
		t.Fatalf("code %d stderr %q", code, stderr)
	}
}
